## Hidden Markov Models

Hidden Markov Models (HMMs) are a statistical model used to represent systems that are assumed to be a Markov process with hidden states. They are widely used in various fields such as speech recognition, natural language processing, and bioinformatics.

Key components of an HMM include:
1. **States**: A finite set of hidden states that the system can be in.

2. **Observations**: A finite set of observable events that are generated by the hidden states.

3. **Transition Probabilities**: The probabilities of transitioning from one hidden state to another.

4. **Emission Probabilities**: The probabilities of an observation being generated from a hidden state.

5. **Initial State Probabilities**: The probabilities of the system starting in each hidden state.

In [360]:
import numpy as np

# Transition matrix
A = np.array([[0.4, 0.4, 0.2],
              [0.1, 0.8, 0.1],
              [0.3, 0.2, 0.5]])

# Initial state: Happy
p = np.array([0.0, 1.0, 0.0])

# Evolve for 10 steps
for i in range(10):
    p = np.dot(p, A)
    print(p)

[0.1 0.8 0.1]
[0.15 0.7  0.15]
[0.175 0.65  0.175]
[0.1875 0.625  0.1875]
[0.19375 0.6125  0.19375]
[0.196875 0.60625  0.196875]
[0.1984375 0.603125  0.1984375]
[0.19921875 0.6015625  0.19921875]
[0.19960938 0.60078125 0.19960938]
[0.19980469 0.60039063 0.19980469]


The forward algorithm is a dynamic programming algorithm used to compute the probability of a sequence of observed events given a hidden Markov model. It is used to calculate the likelihood of a sequence of observations, which can be useful for tasks such as speech recognition and natural language processing.

In [361]:
import numpy as np

def forward_algorithm(obs, hidden_states, transition_matrix, emission_matrix,
                     init=np.array([1/3, 1/3, 1/3])):

    T = len(obs)      # number of time steps
    N = len(hidden_states)  # number of states

    alpha = np.zeros((T, N))

    # Initialization (t = 1)
    O0 = obs_map[obs[0]]
    alpha[0, :] = init * emission_matrix[:, O0]
    print("alpha[0]:", alpha[0])

    # Recursion
    for t in range(1, T):
        Ot = obs_map[obs[t]]
        for j in range(N):
            alpha[t, j] = (np.sum(alpha[t-1, :] * transition_matrix[:, j])
                           * emission_matrix[j, Ot])
        print(f"alpha[{t}]:", alpha[t])

    # Final probability
    P_O = np.sum(alpha[T-1, :])
    print("\nProbability of the observation sequence:", P_O)

In [362]:
observations = ["Walk", "Shop", "Clean", "Walk", "Walk",
                "Shop", "Clean", "Walk", "Clean", "Shop"]

hidden_states = ["Sad", "Happy", "Angry"]

obs_map = {"Walk": 0, "Clean": 1, "Shop": 2}

A = np.array([[0.4, 0.4, 0.2],
              [0.1, 0.8, 0.1],
              [0.3, 0.2, 0.5]])

B = np.array([[0.1, 0.2, 0.7],
              [0.6, 0.3, 0.1],
              [0.2, 0.6, 0.2]])

pi = np.array([1/3, 1/3, 1/3])

forward_algorithm(observations, hidden_states, A, B, pi)

alpha[0]: [0.03333333 0.2        0.06666667]
alpha[1]: [0.03733333 0.01866667 0.012     ]
alpha[2]: [0.00408 0.00968 0.0092 ]
alpha[3]: [0.000536  0.0067296 0.0012768]
alpha[4]: [0.00012704 0.00351206 0.00028371]
alpha[5]: [0.000341   0.00029172 0.00010369]
alpha[6]: [3.93356800e-05 1.17154099e-04 8.95309056e-05]
alpha[7]: [5.43089536e-06 7.64182395e-05 1.28695997e-05]
alpha[8]: [2.73501240e-06 1.97642609e-05 9.09768174e-06]
alpha[9]: [4.05981490e-06 1.87249500e-06 1.41445389e-06]

Probability of the observation sequence: 7.3467637917696e-06
