## Multi-Layer Perceptrons

A multi-layer perceptron (MLP) is a type of feedforward artificial neural network that consists of multiple layers of nodes, including an input layer, one or more hidden layers, and an output layer. Each node in the MLP is a neuron that uses a nonlinear activation function to process the input data. MLPs are commonly used for classification and regression tasks in machine learning.

A perceptron is a single-layer neural network that can only learn linear decision boundaries. In contrast, an MLP can learn complex, non-linear relationships between the input and output data due to its multiple layers and nonlinear activation functions. The hidden layers in an MLP allow it to capture intricate patterns in the data, making it a powerful tool for various machine learning applications.

In [30]:
# Perceptrons in Neural Network
import pandas as pd
import numpy as np

# Create dataset
data = {
    "prio": [120,110,115,100,125,105,118,102,122,108],
    "static_prio": [120,110,115,100,120,105,118,102,120,108],
    "normal_prio": [120,110,115,100,125,105,118,102,122,108],
    "policy": [0,1,0,1,0,1,0,1,0,1],
    "vm_pgoff": [1024,4096,2048,8192,512,6000,1500,7000,900,5000],
    "class": [0,1,0,1,0,1,0,1,0,1]
}

df = pd.DataFrame(data)

# Split features and target
X = df.drop(columns="class")
y = df["class"]

# Convert to NumPy arrays
X = X.values
y = y.values

# Normalize features
X = (X - X.mean(axis=0)) / X.std(axis=0)

print("Normalized Input Matrix X:\n", X)

Normalized Input Matrix X:
 [[ 0.90387691  1.10609006  0.90387691 -1.         -0.97775361]
 [-0.3012923  -0.24280026 -0.3012923   1.          0.17607978]
 [ 0.3012923   0.4316449   0.3012923  -1.         -0.59314248]
 [-1.50646151 -1.59169058 -1.50646151  1.          1.71452431]
 [ 1.50646151  1.10609006  1.50646151 -1.         -1.17005917]
 [-0.90387691 -0.91724542 -0.90387691  1.          0.8912161 ]
 [ 0.66284307  0.836312    0.66284307 -1.         -0.79896953]
 [-1.26542767 -1.32191251 -1.26542767  1.          1.26681291]
 [ 1.14491075  1.10609006  1.14491075 -1.         -1.02432761]
 [-0.54232614 -0.51257832 -0.54232614  1.          0.5156193 ]]


In [31]:
# Weights: 4 neurons × 5 features
W = np.array([
    [0.02, 0.01, 0.015, 0.5, 0.0005],
    [0.03, 0.02, 0.01, 0.4, 0.0003],
    [0.01, 0.015, 0.02, 0.6, 0.0007],
    [0.025, 0.02, 0.012, 0.45, 0.0004]
])

# Bias for each neuron
b = np.array([0.1, 0.1, 0.1, 0.1])

# Initialize output matrix
Z = np.zeros((len(X), len(W)))

# Compute weighted sum
for i in range(len(X)):          # each sample
    for j in range(len(W)):      # each neuron
        z_k = np.dot(W[j], X[i]) + b[j]
        Z[i][j] = z_k

print("Output Matrix Z:\n", Z)

Output Matrix Z:
 [[-0.35779228 -0.24201645 -0.45697677 -0.29482585]
 [ 0.58711481  0.48314513  0.68744248  0.53406661]
 [-0.38543489 -0.27949335 -0.48490176 -0.33045654]
 [ 0.5322142   0.40842209  0.63213096  0.46311292]
 [-0.33679798 -0.21797076 -0.43903385 -0.27260715]
 [ 0.55963746  0.44576738  0.65974886  0.49856813]
 [-0.36883686 -0.25699973 -0.46812931 -0.30906815]
 [ 0.54312431  0.42332469  0.64309525  0.47724765]
 [-0.34937939 -0.23238907 -0.44977836 -0.28592623]
 [ 0.57615061  0.46821007  0.67640247  0.51988861]]


In [32]:
# Sigmoid activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Apply sigmoid element-wise
H = sigmoid(Z)

print("Hidden Layer Output (After Sigmoid):\n", H)

Hidden Layer Output (After Sigmoid):
 [[0.4114941  0.43978949 0.38770326 0.42682283]
 [0.64270287 0.61849028 0.66539775 0.63043108]
 [0.40481674 0.43057799 0.38109532 0.41812954]
 [0.62999939 0.60070946 0.65297249 0.61375239]
 [0.4165875  0.44572204 0.39197121 0.43226716]
 [0.63636865 0.60963242 0.65920397 0.62212278]
 [0.40882211 0.43610138 0.38505911 0.42334221]
 [0.63253891 0.60427854 0.65545281 0.61709774]
 [0.41353293 0.44216279 0.38941347 0.42900148]
 [0.64018118 0.61496002 0.66293529 0.62712172]]


In [33]:
# Output layer parameters
W_out = np.array([0.5, 0.3, 0.4, 0.6])
b_out = 0.1

# Compute weighted sum (vectorized)
z_out = np.dot(H, W_out) + b_out

print("z_out:\n", z_out)

z_out:
 [0.8488589  1.25131627 0.83489762 1.22465297 0.85815914 1.23802931
 0.84327044 1.22999279 0.85258158 1.24602575]


In [34]:
# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Convert to probabilities
y_hat = sigmoid(z_out)

print("Predicted probabilities:\n", y_hat)

Predicted probabilities:
 [0.70032772 0.77752763 0.69738951 0.77288135 0.7022759  0.7752208
 0.69915356 0.77381731 0.70110841 0.77661114]


In [35]:
def binary_cross_entropy(y, y_hat):
    eps = 1e-9  # prevent log(0)
    loss = -np.mean(y * np.log(y_hat + eps) + (1 - y) * np.log(1 - y_hat + eps))
    return loss

loss = binary_cross_entropy(y, y_hat)
print("Loss:", loss)

Loss: 0.7293900487551646


In [36]:
dz = y_hat - y
n = len(y)

dW_out = np.dot(H.T, dz) / n
db_out = np.mean(dz)

In [37]:
learning_rate = 0.01

W_out = W_out - learning_rate * dW_out
b_out = b_out - learning_rate * db_out

print("Updated W_out:", W_out)
print("Updated b_out:", b_out)

Updated W_out: [0.49927637 0.29914891 0.39938605 0.59920831]
Updated b_out: 0.09762368667473544


In [38]:
def backprop_output_layer(H, y, W_out, b_out, lr=0.01):
    # Forward pass
    z_out = np.dot(H, W_out) + b_out
    y_hat = sigmoid(z_out)

    # Error gradient
    dz = y_hat - y
    n = len(y)

    # Gradients
    dW = np.dot(H.T, dz) / n
    db = np.mean(dz)

    # Update parameters
    W_out -= lr * dW
    b_out -= lr * db

    return W_out, b_out, y_hat


# Run one step
W_out, b_out, y_hat = backprop_output_layer(H, y, W_out, b_out)

print("Updated W_out:", W_out)
print("Updated b_out:", b_out)
print("Predicted y:", y_hat)

Updated W_out: [0.49855667 0.29830175 0.39877603 0.59842056]
Updated b_out: 0.09525488851278673
Predicted y: [0.69956653 0.7767872  0.69662909 0.77213793 0.70151428 0.77447885
 0.69839267 0.77307447 0.70034704 0.7758701 ]


In [39]:
# Adam hyperparameters
lr = 0.01
beta1 = 0.9
beta2 = 0.999
epsilon = 1e-8

In [40]:
# Output layer moments
m_w_out = np.zeros_like(W_out)
v_w_out = np.zeros_like(W_out)
m_b_out = 0
v_b_out = 0

# Hidden layer moments
m_w_h = np.zeros_like(W)
v_w_h = np.zeros_like(W)
m_b_h = np.zeros_like(b)
v_b_h = np.zeros_like(b)

# Time step
t = 1

In [41]:
def adam_update(W, b, dW, db, m_w, v_w, m_b, v_b, t,
                lr=0.01, beta1=0.9, beta2=0.999, eps=1e-8):

    # First moment (momentum)
    m_w = beta1 * m_w + (1 - beta1) * dW
    m_b = beta1 * m_b + (1 - beta1) * db

    # Second moment (variance)
    v_w = beta2 * v_w + (1 - beta2) * (dW ** 2)
    v_b = beta2 * v_b + (1 - beta2) * (db ** 2)

    # Bias correction
    m_w_hat = m_w / (1 - beta1 ** t)
    v_w_hat = v_w / (1 - beta2 ** t)
    m_b_hat = m_b / (1 - beta1 ** t)
    v_b_hat = v_b / (1 - beta2 ** t)

    # Parameter update
    W = W - lr * m_w_hat / (np.sqrt(v_w_hat) + eps)
    b = b - lr * m_b_hat / (np.sqrt(v_b_hat) + eps)

    return W, b, m_w, v_w, m_b, v_b

In [42]:
# Initialize Parameters
np.random.seed(42)

input_size = X.shape[1]
hidden_size = 4

W = np.random.randn(hidden_size, input_size) * 0.01
b = np.zeros(hidden_size)

W_out = np.random.randn(hidden_size) * 0.01
b_out = 0.0

In [43]:
# Adam states
m_w = np.zeros_like(W)
v_w = np.zeros_like(W)
m_b = np.zeros_like(b)
v_b = np.zeros_like(b)

m_w_out = np.zeros_like(W_out)
v_w_out = np.zeros_like(W_out)
m_b_out = 0
v_b_out = 0

In [44]:
# Training
epochs = 100
t = 1

for epoch in range(epochs):
    # Forward pass
    Z = np.dot(X, W.T) + b
    H = sigmoid(Z)

    z_out = np.dot(H, W_out) + b_out
    y_hat = sigmoid(z_out)

    # Loss
    loss = binary_cross_entropy(y, y_hat)

    # Backpropagation
    dz_out = y_hat - y

    # Output layer gradients
    dW_out = np.dot(H.T, dz_out) / len(y)
    db_out = np.mean(dz_out)

    # Hidden layer gradients
    dH = dz_out[:, None] * W_out
    dZ = dH * H * (1 - H)

    dW = np.dot(dZ.T, X) / len(X)
    db = np.mean(dZ, axis=0)

    # Adam Updates
    W_out, b_out, m_w_out, v_w_out, m_b_out, v_b_out = adam_update(W_out, b_out, dW_out, db_out,
                                                                   m_w_out, v_w_out, m_b_out, v_b_out, t)

    W, b, m_w, v_w, m_b, v_b = adam_update(W, b, dW, db, m_w, v_w, m_b, v_b, t)
    t += 1

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

Epoch 0, Loss: 0.693118
Epoch 10, Loss: 0.672223
Epoch 20, Loss: 0.608909
Epoch 30, Loss: 0.516830
Epoch 40, Loss: 0.421568
Epoch 50, Loss: 0.339528
Epoch 60, Loss: 0.274847
Epoch 70, Loss: 0.225576
Epoch 80, Loss: 0.188248
Epoch 90, Loss: 0.159703


In [45]:
# Final forward pass
z_out = np.dot(H, W_out) + b_out
y_hat = sigmoid(z_out)

print("Final predicted probabilities:\n", y_hat)
# Convert to classes
predictions = (y_hat >= 0.5).astype(int)

print("Predicted classes:\n", predictions)
print("Actual classes:\n", y)

Final predicted probabilities:
 [0.11486161 0.82734376 0.16367648 0.885503   0.10909123 0.87961767
 0.12481414 0.88430902 0.11187792 0.86301212]
Predicted classes:
 [0 1 0 1 0 1 0 1 0 1]
Actual classes:
 [0 1 0 1 0 1 0 1 0 1]
