## Singular Value Decomposition

Singular Value Decomposition (SVD) is a powerful matrix factorization technique used in various applications, including recommender systems. It decomposes a matrix into three other matrices, capturing the underlying structure of the data. In the context of recommender systems, SVD can be used to predict user preferences and make recommendations based on the latent factors derived from the user-item interaction matrix.

Formula:
$$A = U \Sigma V^T$$

Where:
- $A$ is the original user-item interaction matrix.

- $U$ is the matrix of left singular vectors (user factors).

- $V^T$ is the matrix of right singular vectors (item factors).

- $\Sigma$ is the diagonal matrix of singular values (importance of each factor).

In [1]:
import numpy as np

A = np.array([[5, 4, 2, 3],
              [3, 2, 3, 3],
              [4, 4, 3, 1],
              [1, 2, 3, 1],
              [1, 1, 5, 1]])

ATA = A.T @ A
print(f"A^T * A:\n", ATA)

A^T * A:
 [[52 45 39 30]
 [45 41 37 25]
 [39 37 56 26]
 [30 25 26 21]]


In [2]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(ATA)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [147.87287667  17.6397502    0.45716781   4.03020531]
Eigenvectors:
 [[-0.56906083 -0.47058785 -0.67431945 -0.00318136]
 [-0.50926195 -0.2810943   0.62837252 -0.51651354]
 [-0.54473182  0.82827853 -0.11805972 -0.05730474]
 [-0.34653901 -0.11613676  0.36946334  0.85435345]]


In [3]:
V = eigenvectors
print("V:\n", V)

V:
 [[-0.56906083 -0.47058785 -0.67431945 -0.00318136]
 [-0.50926195 -0.2810943   0.62837252 -0.51651354]
 [-0.54473182  0.82827853 -0.11805972 -0.05730474]
 [-0.34653901 -0.11613676  0.36946334  0.85435345]]


In [4]:
sigma = np.sqrt(eigenvalues)
U = []
for i in range(len(sigma)):
    if sigma[i] > 1e-10:
        ui = (A @ V[:, i]) / sigma[i]
        U.append(ui)

U = np.array(U).T
print("U:\n", U)

U:
 [[-0.57658389 -0.51647263  0.02094737  0.18255697]
 [-0.44402846  0.03868436 -0.01775141  0.67175592]
 [-0.51758805 -0.15191293 -0.24921332 -0.69554897]
 [-0.29344008  0.31807901  0.88400052 -0.17622051]
 [-0.34115286  0.77942783 -0.39456545  0.02397707]]


In [5]:
sigma = np.sqrt(eigenvalues)
Sigma = np.diag(sigma)
print("Sigma:\n", Sigma)

Sigma:
 [[12.1602992   0.          0.          0.        ]
 [ 0.          4.19997026  0.          0.        ]
 [ 0.          0.          0.67614186  0.        ]
 [ 0.          0.          0.          2.00753713]]


In [6]:
A_reconstructed = U @ Sigma @ V.T
print("A_reconstructed:\n", A_reconstructed)

A_reconstructed:
 [[5. 4. 2. 3.]
 [3. 2. 3. 3.]
 [4. 4. 3. 1.]
 [1. 2. 3. 1.]
 [1. 1. 5. 1.]]
